# Explore and download querysets in VIEWS3

This notebook allows you to search for, fetch, and download data from pre-specified querysets in the internal VIEWS database. 

**NOTE: Requires a certificate/access to the VIEWS database.**

In [1]:
from viewser.operations import fetch
from viewser import Queryset, Column
from views_mapper2.label_writer import *

## Browse existing querysets

In [2]:
# !viewser queryset list
# !viewser queryset show "fatalities002_vdem_short"

# Specify the output folder

In [4]:
import os
home = os.path.expanduser("~")

#### Save to your desktop

In [5]:
desktop = home+'/Desktop/'

# Fetch data

In [6]:
# Specify time period

StartOfHistory = 121 # (Jan 1990)
EndOfHistory = 540 # Update as needed

In [7]:
# Specify queryset

chosen_queryset = 'prediction_competition_cm_features'

In [8]:
# Fetch complete dataset 

full_qs = Queryset(chosen_queryset,'country_month') # Change to queryset and level of analysis of interest
full_qs = full_qs.fetch()

100%|██████████| 11.9M/11.9M [00:06<00:00, 1.95MB/s]

Queryset prediction_competition_cm_features read successfully

In [9]:
# Or filter out subset of data

qs_subset = full_qs.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory}')
qs_subset # Displays the subset

                     gleditsch_ward  ged_sb  ged_ns  ged_os  acled_sb  \
month_id country_id
121      1                      110       0       0       0       0.0
         2                      115       0       0       0       0.0
         3                       52       0       0       0       0.0
         4                      101       0       0      12       0.0
         5                      990       0       0       0       0.0
...                             ...     ...     ...     ...       ...
540      242                    510       0       0       0       0.0
         243                    600       0       0       0       3.0
         244                    435       0       0       0       0.0
         245                    625     499       2     159    1499.0
         246                    626       0       0       0       6.0

                     acled_sb_count  acled_os  ged_sb_tsum_24  \
month_id country_id
121      1                      0.0       0.0             0.0
         2                      0.0       0.0             0.0
         3                      0.0       0.0             0.0
         4                      0.0       0.0             0.0
         5                      0.0       0.0             0.0
...                             ...       ...             ...
540      242                    0.0       1.0             0.0
         243                    2.0       0.0             9.0
         244                    0.0       1.0             7.0
         245                  211.0     726.0          8922.0
         246                    5.0      16.0            52.0

                     wdi_sp_pop_totl  ged_sb_tlag_1  ...  ind_efficiency_t48  \
month_id country_id                                  ...
121      1                  752897.0            0.0  ...           43.141952
         2                  408360.0            0.0  ...           20.844640
         3                 1256210.0            0.0  ...           42.245824
         4                19275292.0            0.0  ...          159.866899
         5                  167886.0            0.0  ...            0.000000
...                              ...            ...  ...                 ...
540      242              63588334.0            0.0  ...          614.734859
         243              37076584.0            0.0  ...          126.389217
         244               4614974.0            0.0  ...           47.668220
         245              45657202.0          565.0  ...          171.220998
         246              10748272.0            0.0  ...           24.604523

                     irr_agr_efficiency_t48  services_efficiency_t48  \
month_id country_id
121      1                         0.151779                27.952694
         2                         0.722621                57.289771
         3                         1.671158                35.755839
         4                         0.443153                28.946372
         5                         0.000000                 0.000000
...                                     ...                      ...
540      242                       0.192982                43.054457
         243                       0.432900                56.591798
         244                       0.352241                35.254024
         245                       0.206446                60.772098
         246                       0.017264                24.960320

                     general_efficiency_t48  water_stress_t48  \
month_id country_id
121      1                         1.380676          3.333333
         2                         3.922495          2.950609
         3                        36.015231         17.956469
         4                        26.864392          2.249173
         5                         0.000000          0.000000
...                                     ...               ...
540      242                       7.513882         12.963241
         243                       8.715869         50.751212
         244                       3.932657         13.246217
         245                       2.818789        118.656388
         246                      15.740886          4.226076

                     renewable_internal_pcap_t48  renewable_pcap_t48  \
month_id country_id
121      1                         315260.986388       354505.092577
         2                         264606.831667       264606.831667
         3                           3244.939711         3244.939711
         4                          45295.968642        74555.476336
         5                              0.000000            0.000000
...                                          ...                 ...
540      242                         1491.651069         1709.538672
         243                          804.905080          804.905080
         244                           90.840692         2588.959722
         245                           95.690270          904.273056
         246                         2368.820419         4509.869645

                     splag_1_decay_ged_sb_5  splag_1_decay_ged_os_5  \
month_id country_id
121      1                         0.093750                1.034032
         2                         0.062500                0.062500
         3                         0.000000                0.000000
         4                         1.062500                1.062500
         5                         0.000000                0.000000
...                                     ...                     ...
540      242                       4.753774                4.745371
         243                       0.946784                0.016562
         244                       1.777169                1.036629
         245                       4.798255                3.648036
         246                       5.671701                5.644831

                     splag_1_decay_ged_ns_5
month_id country_id
121      1                         0.093750
         2                         0.062500
         3                         0.000000
         4                         0.093750
         5                         0.000000
...                                     ...
540      242                       3.784548
         243                       0.020268
         244                       1.021954
         245                       3.849195
         246                       5.468309

[78900 rows x 124 columns]

## Save to csv

In [10]:
qs_subset.to_csv(desktop+f'Queryset_{chosen_queryset}_{StartOfHistory}-{EndOfHistory}.csv') # Change name of csv

In [11]:
print("All done")

All done