# Fetch VIEWS data from internal storage 

## Example for fatalities001 (incl. conversion from logged to non-logged output)

**Requires access to VIEWS internal database**

In [1]:
#To plot
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
from matplotlib.animation import PillowWriter
from matplotlib.cm import ScalarMappable
from matplotlib.lines import Line2D
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from textwrap import wrap
from scipy import interpolate
from matplotlib import gridspec
from matplotlib import cm

import seaborn as sns

#To fetch url 
import requests
import json

# sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

# Views 3
from viewser.operations import fetch
from viewser import Queryset, Column
import views_runs
from views_partitioning import data_partitioner, legacy
from stepshift import views
from views_runs import storage, ModelMetadata
from views_runs.storage import store, retrieve, fetch_metadata
from views_forecasts.extensions import *

# For mapping 
import os
from views_mapper2.mapper2 import *
from views_mapper2.BBoxWriter import *
from views_mapper2.dictionary_writer import *
from views_mapper2.label_writer import *
from ingester3.extensions import *

In [2]:
import os
home = os.path.expanduser("~")
desktop = home+'/Desktop/' # (Toggle on to save to desktop)

In [4]:
calib_run_id = 46 #run_id
future = pd.DataFrame.forecasts.read_store(run=calib_run_id, name='cm_genetic_ensemble_f526') # fetching run from storage

pr_46_cm_genetic_ensemble_f526.parquet

In [5]:
future #step_combined is main_mean

feature              step_combined
month_id country_id
527      1                0.014935
         2                0.016678
         3                0.005554
         4                0.946769
         5                0.011209
...                            ...
562      242              0.807649
         243              0.536324
         244              0.514527
         245              5.461447
         246              1.617178

[6876 rows x 1 columns]

In [6]:
future['step_combined'] = np.exp(future['step_combined'])-1 # transforming step_combined to become actual predicted fatalities

In [7]:
future # can save as csv file

feature              step_combined
month_id country_id
527      1                0.015047
         2                0.016818
         3                0.005570
         4                1.577370
         5                0.011272
...                            ...
562      242              1.242629
         243              0.709711
         244              0.672846
         245            234.437940
         246              4.038852

[6876 rows x 1 columns]